### ISSUE TITLE
Change the "clear" button to a "clear results" button in the AQL UI

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#119]
Currently the clear button clears the query, which was immediately apparent to me. ~We should either change the wording to reflect that it just clears the query text or we could update the functionality to clear out the query results, too.~

TODO:
- [x] change the button text to `clear results`
- [x] change its behavior to do so

**Comment by waxlamp** [comment]
I would lean towards just removing the button. The standard way to clear a free-form text field is to select all the text and press backspace (or use `Ctrl-a` etc.).

And I don't think there's a need for a "clear results" button specifically.

Thoughts?

**Comment by AlmightyYakob** [comment]
I agree that we should not let the clear button actually clear the text in the textarea, but I do think we should have a clear button to clear the results. My vote would be to change the text on the button to "Clear Results", and changing it's behavior to do so.

This would also fix another quirk I just noticed, which is if you hit the clear button, it removes the text from the textarea, without any way to recover it. This could be frustrating if you hit the button accidentally after building a complex query. If the clear button no longer clears the textarea, any change done by the user can be undone by pressing `Ctrl-Z` repeatedly.

**Comment by waxlamp** [comment]
> I agree that we should not let the clear button actually clear the text in the textarea, but I do think we should have a clear button to clear the results. My vote would be to change the text on the button to "Clear Results", and changing it's behavior to do so.
> 
> This would also fix another quirk I just noticed, which is if you hit the clear button, it removes the text from the textarea, without any way to recover it. This could be frustrating if you hit the button accidentally after building a complex query. If the clear button no longer clears the textarea, any change done by the user can be undone by pressing `Ctrl-Z` repeatedly.

Sounds good, I'll edit the description and title.
