### ISSUE TITLE
After successfully creating a table, the create table dialog doesn't reset

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#150]
I'm struggling to upload 2 tables back to back without a refresh. It seems that the modal doesn't reset after a successful upload.

Here's a better description:
The modal is full of the data from before (same uploaded data set and column definitions), and going back and stepping through the steps with a new file doesn't work. The "Create Table" button triggers the upload once the table name has been manually changed in the modal

**Comment by waxlamp** [comment]
What do you mean by "reset"?

**Comment by JackWilb** [comment]
The modal is full of the data from before (same uploaded data set and column definitions), and going back and stepping through the steps with a new file doesn't work. The "Create Table" button doesn't trigger the upload to occur

**Comment by waxlamp** [comment]
> The modal is full of the data from before (same uploaded data set and column definitions), and going back and stepping through the steps with a new file doesn't work. The "Create Table" button doesn't trigger the upload to occur

Gotcha, yikes.

Can you update the issue description with this text, and also add in any console or server errors you encounter while trying this?

**Comment by JackWilb** [comment]
I was mistaken, it does trigger the upload if the table name is changed manually (it's not set by updating the file)
