### ISSUE TITLE
Improve data upload

### ISSUE THREAD

**Issue by jtomeck** [multinet-app/multinet-client#158]
Based on a conversation with @gotdairyya, we'd like to potentially plan data upload within workspaces to be a little more streamlined. My suggestion for the UI was:

- Have a single upload button.
- Clicking button brings up an upload "wizard"
- Walks you through uploading node tables -> edge tables -> network creation

We'd need to allow a person to finish the process before network creation if they choose. Maybe something saying "would you like to create a network based on your uploaded tables?" If they say yes, it continues to network creation, if not then just finishes the upload process.

**Comment by waxlamp** [comment]
Keep in mind that there are also ways to upload other (non CSV) files and have those create tables and/or networks in the system. This UX design overhaul should capture those cases as well.

**Comment by JackWilb** [comment]
Should we also allow uploading tables and not making a network right away? Is there a use case for that?

**Comment by waxlamp** [comment]
> Should we also allow uploading tables and not making a network right away? Is there a use case for that?

Definitely yes. I think Jared addressed this in his last paragraph.
