### ISSUE TITLE
Update client to use new API permissions

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-client#177]
This may be better suited in the [MultinetJS](https://github.com/multinet-app/multinetjs) repo. If so, feel free to transfer this issue there.

**Comment by waxlamp** [comment]
> This may be better suited in the [MultinetJS](https://github.com/multinet-app/multinetjs) repo. If so, feel free to transfer this issue there.

Seems like we can keep this issue here, even though the work may involve both this repo and multinetjs.

**Comment by AlmightyYakob** [comment]
Closed via #183
