### ISSUE TITLE
Text in Delete Workspace Dialog Persists

### ISSUE THREAD

**Issue by naglepuff** [multinet-app/multinet-client#190]
I am able to see this small quirk on [multinet.app](multinet.app) and [web.next.multinet.app](web.next.multinet.app).

To reproduce:

1. Go to one of the websites mentioned above
2. Click on the "Delete" icon in the workspace sidebar
3. Enter some text when it asks for a random phrase, then cancel
4. Open up the dialog again by clicking a "Delete" icon
5. The text you just entered remains

I am of the opinion that this text should be cleared when the delete dialog is closed. This might also affect table/network deletion. Not a huge deal, and as far as I can tell it doesn't really impact any functionality, more of a quality-of-life thing.

**Comment by waxlamp** [comment]
I agree that this needs to be fixed. I'm marking it as "good first issue" but feel free to fix it at your own leisure as well.

**Comment by JackWilb** [comment]
Closed via #204
