### ISSUE TITLE
User initial don't display properly in girder4

### ISSUE THREAD

**Issue by naglepuff** [multinet-app/multinet-client#194]
During the calculation of user initials in `LoginMenue.vue`, there is no fallback if `first_name` and `last_name` are `''`, `null` or `undefined`. This doesn't break anything, but we should have placeholder values for this case, and trying to squeeze `undefinedundfined` into the user icon looks bad.

**Comment by waxlamp** [comment]
Not to get too philosophical, but if `undefinedundefined` makes it to the end user, I consider that a broken part of the client.

**Comment by JackWilb** [comment]
Closed via #204
