### ISSUE TITLE
On upload the client is processing the entire dataset to determine types -- slow for large uploads

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#195]
I'm pretty sure the client is processing the entirety of the data to determine the column type before upload. We should put some kind of limit on this to speed it up for the user so that they're not waiting for their browser to finish running our JS before being allowed to upload. I imagine this experience would be notably bad on slow hardware. Maybe, if it's over 1000 (this limit is completely arbitrary and could be much larger) rows, we just say "tell us your types" instead of making an assumption for them.

This affects all branches currently, but is particularly a problem on `girder4` since that branch the corresponding branch in the api enables large file uploads

**Comment by waxlamp** [comment]
Limiting to the first 1000 rows is a good idea. The tradeoff here is against a full accounting for our "category" heuristic, but that's something the user can adjust if the system guesses wrong from the first 1000 rows. (Better still would be to sample the rows randomly but I don't think that would make a big impact vs. just taking the "head" of the rows.)

Did you run into this problem yourself, Jack? How many rows were in your file, and how long do you estimate you had to wait?

**Comment by JackWilb** [comment]
>Did you run into this problem yourself, Jack? How many rows were in your file, and how long do you estimate you had to wait?

I did. I was uploading a table with approximately a million rows (slightly less) and it would take about 20-30 seconds for the preview of the data and the types to show up in the second table of the upload steps.

**Comment by JackWilb** [comment]
Closed via #196. The change is now in the girder4 branch
