### ISSUE TITLE
Need to add form validation

### ISSUE THREAD

**Issue by jtomeck** [multinet-app/multinet-client#23]
Potentially use https://vuetifyjs.com/en/components/forms#vee-validate to add validation to forms app-wide

**Comment by waxlamp** [comment]
@jtomeck, I'm not sure I understand what needs to be done for this issue. Can you provide some guidance?

**Comment by jtomeck** [comment]
Only thing I can remember is that you mentioned things like workspace names you wanted to be all lowercase and that sort of thing, so I brought up adding validation. Otherwise I don't remember where this originated from.

I apparently can't get to this issue unless I click the link in your email. I can't search it or reference it. Strange.

**Comment by waxlamp** [comment]
> Only thing I can remember is that you mentioned things like workspace names you wanted to be all lowercase and that sort of thing, so I brought up adding validation. Otherwise I don't remember where this originated from.
> 

I will go ahead and close this issue, then. If an individual need to validate comes up, we can file a new issue.
