### ISSUE TITLE
_key columns are missing on node tables in network builder

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#236]
This means you can't make tables with links from `_from`/`_to` to `_key`

![image](https://user-images.githubusercontent.com/36867477/171746597-ce05a218-718e-4afe-a4c5-d57caf9050fb.png)

**Comment by AlmightyYakob** [comment]
This isn't meant to be used with existing network tables / tables that are already in the multinet format, it's to be used on tables where you have semantically matching data. So if the `_from` column of `membership` had the actual _values_ of `members`, and the `_to` column had the values of `clubs`.
