### ISSUE TITLE
The network builder fails to build the network with a 500 error

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#239]
Maybe this issue will need to be transferred to the api repo

**Comment by AlmightyYakob** [comment]
What was the body of the error?

**Comment by JackWilb** [comment]
Okay, it seems that Heroku was part of the problem. Now I'm getting a 500 error on the same route:

```
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

It looks like it makes the edge table and is unable to insert any rows into it. I get an empty table for the edges

**Comment by JackWilb** [comment]
This is no longer an issue
