### ISSUE TITLE
Move new table/graph to the top

### ISSUE THREAD

**Issue by jeffbaumes** [multinet-app/multinet-client#27]
Currently they don't line up and could be hidden by long lists of tables/graphs.

![image](https://user-images.githubusercontent.com/81305/66075011-9b643900-e528-11e9-89f1-e0f78d807ad2.png)

**Comment by waxlamp** [comment]
I think I fundamentally misunderstood this issue from the start. The issue is asking for the create button for tables and graphs (not newly created tabled and graphs) to be moved to the top of the list, which has been done already.
