### ISSUE TITLE
Store visualization state and add to visualizations workspace

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet-client#282]
When I'm in an MultiNet workspace, open up a visualization, and customize it to show what I want to show it (a) should be stored, and (b) should be shown in the workspace here: 

![Image](https://user-images.githubusercontent.com/2039375/222814190-0d7bc09c-e932-4653-a1e9-4824391c103f.png)

Jack and I discussed the "google docs" approach: 
* When you create a new visualization, it is untitled initally, but you can add a title. 
* It is automatically stored.
* If you re-open it and continue working on it, it is updated. 
* If you create a new one, it is added. 
* Down the line we want to be able to copy and delete.

**Comment by JackWilb** [comment]
Gives us curated vis for examples
