### ISSUE TITLE
Upgrade to Vuetify >=2.2 and use DataPagination from that release

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-client#32]
See https://github.com/multinet-app/multinet/pull/247/commits/9a922152a616131ef12c79a4eb9e3d12ee35edfc for context.

**Comment by JackWilb** [comment]
yarn.lock shows:
```
vuetify@^2.1.5:
  version "2.5.8"
  resolved "https://registry.yarnpkg.com/vuetify/-/vuetify-2.5.8.tgz#a23e6a7e77b77de0744b53cf1e7c9d40efac0635"
  integrity sha512-paLmNhKTYFD41+14rIHnCo+P1jHbUzwBiMowxs5qXVq8RdRMqRmcy05Sfse1WUu90amPGK2fIFQq5rL2N8zqZg==
```

so it looks like we're on 2.5.8. I think we can close this

**Comment by JackWilb** [comment]
Ah, I see. We need to remove the redundant type definition, instead preferring the one from vuetify
