### ISSUE TITLE
TSLint doesn't catch unused imports

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-client#58]
I'm not sure if it doesn't catch other warnings, or what they may be, but this is the use case that I stumbled upon.

**Comment by JackWilb** [comment]
If we end up migrating to eslint these might be useful:
- [tslint conf to eslint conf](https://github.com/typescript-eslint/tslint-to-eslint-config)
- [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)
