### ISSUE TITLE
Renaming a workspace doesn't instantly update it everywhere

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#78]
When renaming a workspace using the top bar, the sidebar becomes out of sync. This means that when you navigate to a different workspace and back to the renamed one (which still shows the old name in the sidebar), the api calls start giving errors since the workspace (with the original name) no longer exists. This behavior is fixed on a full client refresh

Steps to reproduce:
Rename a workspace

**Comment by waxlamp** [comment]
This sounds like a time when we need to figure out how to get the VueX store to update its state. This may be as simple as issuing the appropriate action dispatch in the same circumstances that we invalidate the cache.

For now this can be manual, but we should think about a way for the server to indicate to the client that it should query for fresh data.

**Comment by JackWilb** [comment]
This has been resolved
