### ISSUE TITLE
The landing page information isn't properly aligned

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-client#92]
The white space on the right side of the blue box is smaller than it is on the left. This seems to be an artifact of the flexbox it's inside of. I drew some black arrows on the image to show you what I mean.

<img width="1678" alt="Screen Shot 2020-05-26 at 5 12 04 PM" src="https://user-images.githubusercontent.com/36867477/82959140-8dc35e00-9fa6-11ea-9e56-62e1cde060f7.png">

**Comment by waxlamp** [comment]
This is very low priority, so @jtomeck, if you find yourself with a need for a low-intensity, low-priority task, please take a look at this.
